const countriesCodes = {
    "AL": "Albania",
    "AT": "Austria",
    "BE": "Belgium",
    "BA": "Bosnia and Herzegovina",
    "BY": "Belarus",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "ME": "Montenegro",
    "CZ": "Czechia",
    "DK": "Denmark",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "GR": "Greece",
    "ES": "Spain",
    "IE": "Ireland",
    "IS": "Iceland",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MK": "Macedonia",
    "MD": "Moldova",
    "NL": "Netherlands",
    "NO": "Norway",
    "DE": "Germany",
    "PL": "Poland",
    "PT": "Portugal",
    "RU": "Russia",
    "RO": "Romania",
    "RS": "Serbia",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "CH": "Switzerland",
    "SE": "Sweden",
    "UA": "Ukraine",
    "GB": "United Kingdom",
    "HU": "Hungary",
    "IT": "Italy",
    "XK": "Kosovo",

    /*
    "AD": "Andorra",
    "CY": "Cyprus",
    "KZ": "Kazahstan",
    "LI": "Liechtenstein",
    "MT": "Malta",
    "MC": "Monaco",
    "SM": "San Marino",
    "TR": "Turkey",
    "VA": "Vatican"
    */
};

export default countriesCodes;